@echo off
echo Starting Smart Attendance System Frontend...

echo Checking for existing build folder...
if exist .next (
    echo Cleaning existing build for a fresh start...
    rmdir /s /q .next
)

echo Ensuring all dependencies are installed...
call npm install

echo Starting development server...
call npm run dev
