@echo off
echo Starting Smart Attendance System Backend...

echo Checking PostgreSQL connection...
npx ts-node src/scripts/test-postgres-connection.ts

echo Starting server...
npx ts-node src/index.ts
