version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - attendance-network

  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/attendance
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRE=30d
      - EMAIL_HOST=smtp.example.com
      - EMAIL_PORT=587
      - EMAIL_USER=user@example.com
      - EMAIL_PASS=password
      - EMAIL_FROM=noreply@attendance.edu
      - CLIENT_URL=http://localhost:3000
      - COLLEGE_DOMAIN=iiitmanipur.ac.in
    networks:
      - attendance-network

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    networks:
      - attendance-network

networks:
  attendance-network:
    driver: bridge

volumes:
  mongodb_data: