version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: attendance-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../backend/prisma/setup-postgres.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - attendance-network

networks:
  attendance-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local